import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex w-full relative h-screen overflow-hidden">
      <Sidebar />
      <div className="w-full overflow-y-auto">{children}</div>
    </div>
  );
}
