import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";
import MobileNav from "../../components/MobileNav";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex lg:flex-row flex-col w-full relative h-screen overflow-hidden">
      <Sidebar />
      <MobileNav />
      <div className="w-full overflow-y-auto relative">{children}</div>
    </div>
  );
}
